Added partial volume data
GrammerhubTeam/convertagram pull request #4
Opened 2021-02-08 18:01 UTC by ssmodish

2021-02-08 18:28 UTC, DonaldMurillo requested changes
I am not sure about the exponent on the units. we should probably discuss it during meetup
also there seem to be some of those units that the unit is not quite right, ltr should not be the unit for liter. we should avoid having special characters on the property index

2021-02-09 00:14 UTC, ssmodish commented
OK, special chars are removed

2021-02-09 03:03 UTC, ssmodish commented
And spaces from the units and base have been removed as well

2021-02-11 00:38 UTC, DonaldMurillo approved these changes

2021-02-11 00:38 UTC, merged